export default [
  { word: "about", meaning: "concerning or regarding something" },
  { word: "above", meaning: "at a higher level or position" },
  { word: "abroad", meaning: "in or to a foreign country" },
  { word: "absorb", meaning: "to soak up or take in" },
  { word: "abuse", meaning: "to use something wrongly or harmfully" },
  { word: "accept", meaning: "to agree to receive or take" },
  { word: "access", meaning: "the ability to enter or use" },
  { word: "accuse", meaning: "to charge someone with a wrongdoing" },
  { word: "across", meaning: "from one side to another" },
  { word: "action", meaning: "the process of doing something" },
  { word: "active", meaning: "engaged in movement or participation" },
  { word: "actor", meaning: "a person who performs in plays or films" },
  { word: "actual", meaning: "real or existing in fact" },
  { word: "adapt", meaning: "to adjust to new conditions" },
  { word: "adjust", meaning: "to change slightly for a better fit" },
  { word: "admire", meaning: "to regard with respect or approval" },
  { word: "admit", meaning: "to confess or acknowledge something" },
  { word: "adopt", meaning: "to take up or accept as one’s own" },
  { word: "adult", meaning: "a fully grown person" },
  { word: "advice", meaning: "a recommendation or guidance" },
  { word: "advise", meaning: "to offer suggestions or recommendations" },
  { word: "affair", meaning: "an event or matter of concern" },
  { word: "affect", meaning: "to influence or change" },
  { word: "afford", meaning: "to have the means to do something" },
  { word: "afraid", meaning: "feeling fear or anxiety" },
  { word: "after", meaning: "following in time or order" },
  { word: "again", meaning: "once more or another time" },
  { word: "agency", meaning: "an organization providing a service" },
  { word: "agenda", meaning: "a list of items to be discussed" },
  { word: "agent", meaning: "a person who acts on behalf of another" },
  { word: "agree", meaning: "to share the same opinion or consent" },
  { word: "ahead", meaning: "in front or in advance" },
  { word: "album", meaning: "a collection of music or photos" },
  { word: "alive", meaning: "having life or being active" },
  { word: "allow", meaning: "to permit or enable" },
  { word: "almost", meaning: "nearly but not quite" },
  { word: "alone", meaning: "without others or by oneself" },
  { word: "along", meaning: "moving in a linear direction" },
  { word: "alter", meaning: "to change or modify" },
  { word: "always", meaning: "at all times or continuously" },
  { word: "among", meaning: "in the middle of multiple things" },
  { word: "amount", meaning: "a quantity or sum of something" },
  { word: "anger", meaning: "a strong feeling of displeasure" },
  { word: "angle", meaning: "the space between two intersecting lines" },
  { word: "angry", meaning: "feeling or showing strong displeasure" },
  { word: "animal", meaning: "a living organism that is not a plant" },
  { word: "annual", meaning: "happening once a year" },
  { word: "answer", meaning: "a response to a question" },
  { word: "anyone", meaning: "any person" },
  { word: "anyway", meaning: "regardless or in any case" },
  { word: "apart", meaning: "separated or at a distance" },
  { word: "appeal", meaning: "a request for a decision to be changed" },
  { word: "appear", meaning: "to become visible or present" },
  { word: "apple", meaning: "a round fruit with red or green skin" },
  { word: "apply", meaning: "to make a request or use something" },
  { word: "argue", meaning: "to express disagreement" },
  { word: "arise", meaning: "to emerge or come into being" },
  { word: "armed", meaning: "equipped with weapons" },
  { word: "around", meaning: "in a surrounding area or circle" },
  { word: "arrest", meaning: "to take into legal custody" },
  { word: "arrive", meaning: "to reach a destination" },
  { word: "artist", meaning: "a person who creates art" },
];
