export default [
  { word: "absolutely", meaning: "completely or totally" },
  { word: "accompany", meaning: "to go along with someone or something" },
  { word: "accomplish", meaning: "to successfully complete something" },
  { word: "according", meaning: "as stated by or in agreement with" },
  {
    word: "achievement",
    meaning: "something completed successfully, often through effort",
  },
  { word: "acknowledge", meaning: "to recognize or admit something" },
  {
    word: "additional",
    meaning: "extra or more than what was originally present",
  },
  {
    word: "adjustment",
    meaning: "a small change to improve or adapt something",
  },
  {
    word: "administration",
    meaning: "the process of managing an organization or government",
  },
  {
    word: "administrator",
    meaning: "a person responsible for running an organization or system",
  },
  {
    word: "admission",
    meaning: "the process of entering a place or accepting a truth",
  },
  {
    word: "adolescent",
    meaning: "a young person between childhood and adulthood",
  },
  { word: "advantage", meaning: "a benefit or favorable condition" },
  { word: "adventure", meaning: "an exciting or unusual experience" },
  {
    word: "advertising",
    meaning: "promoting products or services to attract customers",
  },
  { word: "afternoon", meaning: "the time of day between noon and evening" },
  { word: "aggressive", meaning: "forceful, determined, or ready to attack" },
  {
    word: "agreement",
    meaning: "a mutual arrangement or contract between parties",
  },
  { word: "agricultural", meaning: "related to farming or cultivation" },
  { word: "alternative", meaning: "another option or choice" },
  { word: "anniversary", meaning: "the yearly celebration of an event" },
  { word: "anticipate", meaning: "to expect or predict something in advance" },
  { word: "apartment", meaning: "a living space within a building" },
  { word: "apparently", meaning: "seemingly or as far as one can tell" },
  { word: "appearance", meaning: "the way something looks or seems" },
  {
    word: "application",
    meaning: "a request for something or a computer program",
  },
  { word: "appointment", meaning: "a scheduled meeting or arrangement" },
  {
    word: "appreciate",
    meaning: "to recognize the value of something or be thankful",
  },
  { word: "appropriate", meaning: "suitable or proper in the circumstances" },
  { word: "approximately", meaning: "close to but not exactly" },
  { word: "architect", meaning: "a person who designs buildings" },
  { word: "arrangement", meaning: "a plan or organization of things" },
  { word: "assessment", meaning: "the evaluation or analysis of something" },
  { word: "assignment", meaning: "a task or duty given to someone" },
  { word: "assistance", meaning: "help or support provided to someone" },
  { word: "assistant", meaning: "a person who helps another in a job or task" },
  { word: "associate", meaning: "to connect or relate to something" },
  {
    word: "association",
    meaning: "a group of people organized for a common purpose",
  },
  { word: "assumption", meaning: "a belief taken as true without proof" },
  { word: "atmosphere", meaning: "the surrounding air or mood of a place" },
  { word: "attention", meaning: "the act of focusing on something" },
  { word: "attractive", meaning: "pleasing to look at or appealing" },
  { word: "attribute", meaning: "a characteristic or quality of something" },
  {
    word: "authority",
    meaning: "the power or right to give orders and make decisions",
  },
  { word: "available", meaning: "ready for use or accessible" },
  { word: "awareness", meaning: "knowledge or perception of a situation" },
  {
    word: "background",
    meaning: "a person’s history or the setting of something",
  },
  { word: "basically", meaning: "in the simplest terms or fundamentally" },
  { word: "basketball", meaning: "a sport played with a ball and hoop" },
  { word: "beautiful", meaning: "pleasing to the senses or mind" },

  { word: "beginning", meaning: "the start or first part of something" },
  {
    word: "biological",
    meaning: "related to living organisms or life processes",
  },
  { word: "boyfriend", meaning: "a male partner in a romantic relationship" },
  { word: "breakfast", meaning: "the first meal of the day" },
  { word: "brilliant", meaning: "very bright or intelligent" },
  { word: "calculate", meaning: "to determine something mathematically" },
  {
    word: "candidate",
    meaning: "a person who is applying for a position or role",
  },
  { word: "capability", meaning: "the ability to do something" },
  { word: "carefully", meaning: "with caution and attention to detail" },
  { word: "celebrate", meaning: "to mark a special event with joy" },
  { word: "celebration", meaning: "a special event to mark an occasion" },
  { word: "celebrity", meaning: "a famous person" },
  { word: "certainly", meaning: "without doubt; definitely" },
  { word: "challenge", meaning: "a difficult task or test of ability" },
  {
    word: "championship",
    meaning: "a competition to determine the best team or player",
  },
  { word: "character", meaning: "the qualities or traits of a person" },
  { word: "characteristic", meaning: "a distinguishing feature or quality" },
  { word: "characterize", meaning: "to describe the qualities of something" },
  { word: "childhood", meaning: "the period of being a child" },
  { word: "chocolate", meaning: "a sweet treat made from cocoa" },
  { word: "cholesterol", meaning: "a fatty substance found in blood" },
  { word: "Christian", meaning: "related to Christianity or its followers" },
  {
    word: "Christmas",
    meaning: "a holiday celebrating the birth of Jesus Christ",
  },
  {
    word: "cigarette",
    meaning: "a thin tube of tobacco rolled in paper for smoking",
  },
  {
    word: "circumstance",
    meaning: "a condition or fact affecting a situation",
  },
  { word: "classroom", meaning: "a room where lessons take place" },
  { word: "coalition", meaning: "a group formed for a common purpose" },
  { word: "cognitive", meaning: "related to thinking and mental processes" },
  { word: "colleague", meaning: "a coworker or associate in a profession" },
  { word: "collection", meaning: "a group of things gathered together" },
  { word: "collective", meaning: "done by a group rather than an individual" },
  { word: "combination", meaning: "a mix or blend of two or more things" },
  { word: "comfortable", meaning: "providing ease and relaxation" },
  { word: "commander", meaning: "a person in charge of a group or operation" },
  { word: "commercial", meaning: "related to business or trade" },
  {
    word: "commission",
    meaning: "a group given authority or a payment for a service",
  },
  { word: "commitment", meaning: "a dedication to a cause or activity" },
  {
    word: "committee",
    meaning: "a group of people appointed for a specific function",
  },
  { word: "communicate", meaning: "to share information with others" },
  { word: "communication", meaning: "the exchange of information" },
  { word: "community", meaning: "a group of people living in the same area" },
  {
    word: "comparison",
    meaning: "the act of examining similarities and differences",
  },
  {
    word: "competition",
    meaning: "a contest where individuals or groups compete",
  },
  { word: "competitive", meaning: "involving rivalry or the desire to win" },
  {
    word: "competitor",
    meaning: "a person or group that competes against others",
  },
  { word: "complaint", meaning: "an expression of dissatisfaction" },
  { word: "completely", meaning: "totally; entirely" },
  { word: "complicated", meaning: "difficult to understand or deal with" },
  { word: "component", meaning: "a part of a larger system or whole" },
  {
    word: "composition",
    meaning: "the makeup of something or a piece of writing",
  },
];
