export default [
  { word: "abandon", meaning: "to leave something or someone completely" },
  { word: "ability", meaning: "the power or skill to do something" },
  { word: "abortion", meaning: "the termination of a pregnancy" },
  { word: "absence", meaning: "the state of being away or not present" },
  { word: "absolute", meaning: "complete or total" },
  { word: "academic", meaning: "related to education or scholarship" },
  { word: "accident", meaning: "an unexpected event causing damage or injury" },
  {
    word: "account",
    meaning: "a record or statement of financial transactions",
  },
  { word: "accurate", meaning: "correct and free from errors" },
  { word: "achieve", meaning: "to accomplish or reach a goal" },
  { word: "acquire", meaning: "to gain or obtain something" },
  {
    word: "activist",
    meaning: "a person who campaigns for social or political change",
  },
  { word: "activity", meaning: "something that is done for a purpose" },
  { word: "actress", meaning: "a female performer in movies or plays" },
  { word: "actually", meaning: "in fact or really" },
  { word: "addition", meaning: "the process of adding things together" },
  { word: "address", meaning: "the location of a place or a formal speech" },
  {
    word: "adequate",
    meaning: "sufficient or enough for a particular purpose",
  },
  { word: "advance", meaning: "to move forward or progress" },
  { word: "advanced", meaning: "at a higher level of knowledge or skill" },
  {
    word: "adviser",
    meaning: "a person who gives guidance or recommendations",
  },
  { word: "advocate", meaning: "a person who supports a cause or policy" },
  { word: "African", meaning: "relating to Africa or its people" },
  { word: "against", meaning: "in opposition to something" },
  { word: "aircraft", meaning: "a vehicle capable of flying in the air" },
  { word: "airline", meaning: "a company that provides air travel services" },
  { word: "airport", meaning: "a place where aircraft take off and land" },
  {
    word: "alcohol",
    meaning: "a substance found in drinks like beer and wine",
  },
  { word: "alliance", meaning: "a partnership between groups or countries" },
  { word: "already", meaning: "before a particular time" },
  { word: "although", meaning: "despite the fact that" },
  { word: "amazing", meaning: "causing great wonder or surprise" },
  { word: "American", meaning: "related to the United States or its people" },
  { word: "analysis", meaning: "a detailed examination of something" },
  {
    word: "analyst",
    meaning: "a person who studies or examines something carefully",
  },
  { word: "analyze", meaning: "to examine something in detail" },
  { word: "ancient", meaning: "very old or from the distant past" },
  { word: "announce", meaning: "to make something publicly known" },
  { word: "another", meaning: "one more of the same kind" },
  { word: "anxiety", meaning: "a feeling of worry or nervousness" },
  { word: "anybody", meaning: "any person at all" },
  { word: "anymore", meaning: "no longer or not now" },
  { word: "anything", meaning: "any object, event, or matter" },
  { word: "anywhere", meaning: "in any place or location" },
  { word: "apparent", meaning: "clearly visible or understood" },
  { word: "appoint", meaning: "to assign someone to a position" },
  {
    word: "approach",
    meaning: "to come near to something or a way of dealing with something",
  },
  { word: "approval", meaning: "acceptance or agreement" },
  { word: "approve", meaning: "to officially accept or allow" },
  { word: "argument", meaning: "a discussion in which people disagree" },
];
